# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="qwerty123",
            database="login")    

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameTextField = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameTextField.setGeometry(QtCore.QRect(490, 160, 113, 22))
        self.usernameTextField.setObjectName("usernameTextField")
        self.passwordtextfield = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordtextfield.setGeometry(QtCore.QRect(490, 220, 113, 22))
        self.passwordtextfield.setObjectName("passwordtextfield")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(500, 320, 93, 28))
        self.loginButton.setObjectName("loginButton")
        self.loginButton.clicked.connect(self.clickme)
        self.signupbutton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.signupbutton.setGeometry(QtCore.QRect(500, 380, 222, 48))
        self.signupbutton.setObjectName("signupbutton")
        self.usernamelabel = QtWidgets.QLabel(self.centralwidget)
        self.usernamelabel.setGeometry(QtCore.QRect(430, 130, 55, 16))
        self.usernamelabel.setObjectName("usernamelabel")
        self.passwordlabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordlabel.setGeometry(QtCore.QRect(430, 200, 55, 16))
        self.passwordlabel.setObjectName("passwordlabel")
        MainWindow.setCentralWidget(self.centralwidget)
       
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginButton.setText(_translate("MainWindow", "login"))
        self.signupbutton.setText(_translate("MainWindow", "signup"))
        self.usernamelabel.setText(_translate("MainWindow", "username"))
        self.passwordlabel.setText(_translate("MainWindow", "password"))
    
    def clickme(self):
        print("clicked")
        self.username = self.usernameTextField.text()
        self.password = self.passwordtextfield.text()
        print(self.username)
        print(self.password)
        
        mycursor = self.mydb.cursor()
        mycursor.execute("INSERT INTO registered_accounts (userid, username, password, email) VALUES (%s, %s, %s, %s)", (12, self.username, self.password, "ahmad@123.com"))

        print(mycursor.fetchall())


if __name__ == "__main__":  
  
    import sys
   
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
   
    MainWindow.show()


    sys.exit(app.exec())

   
  
  
