# Form implementation generated from reading ui file 'signup_page.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_MainWindow(object):
    mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="psudo",
            database="login")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 461, 371))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.usernamelabel = QtWidgets.QLabel(self.page_1)
        self.usernamelabel.setGeometry(QtCore.QRect(130, 50, 55, 16))
        self.usernamelabel.setObjectName("usernamelabel")
        self.passwordlabel = QtWidgets.QLabel(self.page_1)
        self.passwordlabel.setGeometry(QtCore.QRect(130, 100, 55, 16))
        self.passwordlabel.setObjectName("passwordlabel")
        self.loginButton = QtWidgets.QPushButton(self.page_1)
        self.loginButton.setGeometry(QtCore.QRect(180, 160, 93, 28))
        self.loginButton.setObjectName("loginButton")
        self.loginButton.clicked.connect(self.switch_page)
        self.signupbutton = QtWidgets.QCommandLinkButton(self.page_1)
        self.signupbutton.setGeometry(QtCore.QRect(130, 220, 222, 48))
        self.signupbutton.setObjectName("signupbutton")
        self.signupbutton.clicked.connect(self.switch_page)
        self.usernameTextField = QtWidgets.QLineEdit(self.page_1)
        self.usernameTextField.setGeometry(QtCore.QRect(230, 50, 113, 22))
        self.usernameTextField.setMaxLength(15)
        self.usernameTextField.setObjectName("usernameTextField")
        self.passwordtextfield = QtWidgets.QLineEdit(self.page_1)
        self.passwordtextfield.setGeometry(QtCore.QRect(230, 100, 113, 22))
        self.passwordtextfield.setMaxLength(255)
        self.passwordtextfield.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordtextfield.setObjectName("passwordtextfield")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.username_signup_label = QtWidgets.QLabel(self.page_2)
        self.username_signup_label.setGeometry(QtCore.QRect(100, 10, 55, 16))
        self.username_signup_label.setObjectName("username_signup_label")
        self.username_signuptextfield = QtWidgets.QLineEdit(self.page_2)
        self.username_signuptextfield.setGeometry(QtCore.QRect(190, 10, 113, 22))
        self.username_signuptextfield.setMaxLength(15)
        self.username_signuptextfield.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.username_signuptextfield.setObjectName("username_signuptextfield")
        self.website_signup_label = QtWidgets.QLabel(self.page_2)
        self.website_signup_label.setGeometry(QtCore.QRect(100, 40, 55, 16))
        self.website_signup_label.setObjectName("website_signup_label")
        self.website_signuptextfield = QtWidgets.QLineEdit(self.page_2)
        self.website_signuptextfield.setGeometry(QtCore.QRect(190, 40, 113, 22))
        self.website_signuptextfield.setMaxLength(255)
        self.website_signuptextfield.setObjectName("website_signuptextfield")
        self.email_signup_label = QtWidgets.QLabel(self.page_2)
        self.email_signup_label.setGeometry(QtCore.QRect(110, 70, 55, 16))
        self.email_signup_label.setObjectName("email_signup_label")
        self.email_signuptextfield = QtWidgets.QLineEdit(self.page_2)
        self.email_signuptextfield.setGeometry(QtCore.QRect(190, 70, 113, 22))
        self.email_signuptextfield.setMaxLength(100)
        self.email_signuptextfield.setObjectName("email_signuptextfield")
        self.city_signup_label = QtWidgets.QLabel(self.page_2)
        self.city_signup_label.setGeometry(QtCore.QRect(110, 110, 55, 16))
        self.city_signup_label.setObjectName("city_signup_label")
        self.phone_signup_label = QtWidgets.QLabel(self.page_2)
        self.phone_signup_label.setGeometry(QtCore.QRect(110, 150, 55, 16))
        self.phone_signup_label.setObjectName("phone_signup_label")
        self.phone_signuptextfield = QtWidgets.QLineEdit(self.page_2)
        self.phone_signuptextfield.setGeometry(QtCore.QRect(190, 150, 113, 22))
        self.phone_signuptextfield.setMaxLength(11)
        self.phone_signuptextfield.setFrame(True)
        self.phone_signuptextfield.setObjectName("phone_signuptextfield")
        self.password_signup_label = QtWidgets.QLabel(self.page_2)
        self.password_signup_label.setGeometry(QtCore.QRect(110, 200, 55, 16))
        self.password_signup_label.setObjectName("password_signup_label")
        self.password_signuptextfield = QtWidgets.QLineEdit(self.page_2)
        self.password_signuptextfield.setGeometry(QtCore.QRect(190, 190, 113, 22))
        self.password_signuptextfield.setText("")
        self.password_signuptextfield.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_signuptextfield.setReadOnly(False)
        self.password_signuptextfield.setObjectName("password_signuptextfield")
        self.confirmpassword_signup_label = QtWidgets.QLabel(self.page_2)
        self.confirmpassword_signup_label.setGeometry(QtCore.QRect(80, 240, 101, 16))
        self.confirmpassword_signup_label.setObjectName("confirmpassword_signup_label")
        self.confirmpassword_signuptextfield = QtWidgets.QLineEdit(self.page_2)
        self.confirmpassword_signuptextfield.setGeometry(QtCore.QRect(190, 240, 113, 22))
        self.confirmpassword_signuptextfield.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirmpassword_signuptextfield.setObjectName("confirmpassword_signuptextfield")
        self.signup_pushbutton = QtWidgets.QPushButton(self.page_2)
        self.signup_pushbutton.setGeometry(QtCore.QRect(200, 280, 93, 28))
        self.signup_pushbutton.setObjectName("signup_pushbutton")
        self.signup_pushbutton.clicked.connect(self.switch_page)
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(190, 110, 111, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.signin_LinkButton = QtWidgets.QCommandLinkButton(self.page_2)
        self.signin_LinkButton.setGeometry(QtCore.QRect(140, 320, 185, 41))
        self.signin_LinkButton.setIconSize(QtCore.QSize(20, 20))
        self.signin_LinkButton.setObjectName("signin_LinkButton")
        self.signin_LinkButton.clicked.connect(self.switch_page)
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernamelabel.setText(_translate("MainWindow", "username"))
        self.passwordlabel.setText(_translate("MainWindow", "password"))
        self.loginButton.setText(_translate("MainWindow", "login"))
        self.signupbutton.setText(_translate("MainWindow", "signup"))
        self.username_signup_label.setText(_translate("MainWindow", "username"))
        self.website_signup_label.setText(_translate("MainWindow", "website"))
        self.email_signup_label.setText(_translate("MainWindow", "email"))
        self.city_signup_label.setText(_translate("MainWindow", "city"))
        self.phone_signup_label.setText(_translate("MainWindow", "phone"))
        self.password_signup_label.setText(_translate("MainWindow", "password"))
        self.confirmpassword_signup_label.setText(_translate("MainWindow", "confirm password"))
        self.signup_pushbutton.setText(_translate("MainWindow", "Sign Up"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Islamabad"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Lahore"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Karachi"))
        self.signin_LinkButton.setText(_translate("MainWindow", "Sign In"))

    def switch_page(self):
        if self.stackedWidget.currentIndex() == 0:
            self.stackedWidget.setCurrentIndex(1)
        else:
            self.signup()
            self.stackedWidget.setCurrentIndex(0)

    def signup(self):
        username = self.username_signuptextfield.text()
        password = self.password_signuptextfield.text()
        website= self.website_signuptextfield.text()
        email=self.email_signuptextfield.text()
        city=self.city_signuptextfield.text()
        phone=self.phone_signuptextfield.text()
        confirmpassword= self.confirmpassword_signuptextfield.text()

        if(password != confirmpassword):
            print("password not matched")
            self.errormsg_signup_label = QtWidgets.QLabel(self.centralwidget)
            self.errormsg_signup_label.setGeometry(QtCore.QRect(250,530,55, 16))
            self.errormsg_signup_label.setObjectName("password not matched")
        else:
            mycursor = self.mydb.cursor()
            mycursor.execute("INSERT INTO sign_up (username, password, website, email, city, Phone_Number) VALUES (%s, %s, %s, %s, %s, %s)", (username, password, website, email, city, phone))

            mycursor.execute("SELECT * FROM sign_up")
            print(mycursor.fetchall())

            self.mydb.commit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
