# Form implementation generated from reading ui file 'signup_page.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="qwerty123",
            database="login")   

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username_signup_label = QtWidgets.QLabel(self.centralwidget)
        self.username_signup_label.setGeometry(QtCore.QRect(150, 130, 55, 16))
        self.username_signup_label.setObjectName("username_signup_label")
        self.website_signup_label = QtWidgets.QLabel(self.centralwidget)
        self.website_signup_label.setGeometry(QtCore.QRect(150, 200, 55, 16))
        self.website_signup_label.setObjectName("website_signup_label")
        self.email_signup_label = QtWidgets.QLabel(self.centralwidget)
        self.email_signup_label.setGeometry(QtCore.QRect(150, 260, 55, 16))
        self.email_signup_label.setObjectName("email_signup_label")
        self.city_signup_label = QtWidgets.QLabel(self.centralwidget)
        self.city_signup_label.setGeometry(QtCore.QRect(150, 320, 55, 16))
        self.city_signup_label.setObjectName("city_signup_label")
        self.phone_signup_label = QtWidgets.QLabel(self.centralwidget)
        self.phone_signup_label.setGeometry(QtCore.QRect(150, 370, 55, 16))
        self.phone_signup_label.setObjectName("phone_signup_label")
        self.password_signup_label = QtWidgets.QLabel(self.centralwidget)
        self.password_signup_label.setGeometry(QtCore.QRect(150, 430, 55, 16))
        self.password_signup_label.setObjectName("password_signup_label")
        self.confirmpassword_signup_label = QtWidgets.QLabel(self.centralwidget)
        self.confirmpassword_signup_label.setGeometry(QtCore.QRect(110, 490, 121, 16))
        self.confirmpassword_signup_label.setObjectName("confirmpassword_signup_label")
        self.signup_button = QtWidgets.QPushButton(self.centralwidget)
        self.signup_button.setGeometry(QtCore.QRect(300, 530, 93, 28))
        self.signup_button.setObjectName("signup")
        self.signup_button.clicked.connect(self.clickme)
        self.username_signuptextfield = QtWidgets.QLineEdit(self.centralwidget)
        self.username_signuptextfield.setGeometry(QtCore.QRect(270, 130, 113, 22))
        self.username_signuptextfield.setObjectName("username_signuptextfield")
        self.website_signuptextfield = QtWidgets.QLineEdit(self.centralwidget)
        self.website_signuptextfield.setGeometry(QtCore.QRect(260, 210, 113, 22))
        self.website_signuptextfield.setObjectName("website_signuptextfield")
        self.email_signuptextfield = QtWidgets.QLineEdit(self.centralwidget)
        self.email_signuptextfield.setGeometry(QtCore.QRect(250, 270, 113, 22))
        self.email_signuptextfield.setObjectName("email_signuptextfield")
        self.city_signuptextfield = QtWidgets.QLineEdit(self.centralwidget)
        self.city_signuptextfield.setGeometry(QtCore.QRect(250, 330, 113, 22))
        self.city_signuptextfield.setObjectName("city_signuptextfield")
        self.phone_signuptextfield = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_signuptextfield.setGeometry(QtCore.QRect(240, 380, 113, 22))
        self.phone_signuptextfield.setObjectName("phone_signuptextfield")
        self.password_signuptextfield = QtWidgets.QLineEdit(self.centralwidget)
        self.password_signuptextfield.setGeometry(QtCore.QRect(240, 440, 113, 22))
        self.password_signuptextfield.setObjectName("password_signuptextfield")
        self.confirmpassword_signuptextfield = QtWidgets.QLineEdit(self.centralwidget)
        self.confirmpassword_signuptextfield.setGeometry(QtCore.QRect(240, 490, 113, 22))
        self.confirmpassword_signuptextfield.setObjectName("confirmpassword_signuptextfield")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username_signup_label.setText(_translate("MainWindow", "username"))
        self.website_signup_label.setText(_translate("MainWindow", "website"))
        self.email_signup_label.setText(_translate("MainWindow", "email"))
        self.city_signup_label.setText(_translate("MainWindow", "city"))
        self.phone_signup_label.setText(_translate("MainWindow", "phone"))
        self.password_signup_label.setText(_translate("MainWindow", "password"))
        self.confirmpassword_signup_label.setText(_translate("MainWindow", "confirm password"))
        self.signup_button.setText(_translate("MainWindow", "PushButton"))
    
    def clickme(self):
       
        username = self.username_signuptextfield.text()
        password = self.password_signuptextfield.text()
        website= self.website_signuptextfield.text()
        email=self.email_signuptextfield.text()
        city=self.city_signuptextfield.text()
        phone=self.phone_signuptextfield.text()
        confirmpassword= self.confirmpassword_signuptextfield.text()

       
        print(username)
        print(password)       
        print(website) 
        print(email)
        print(city)
        print(phone)
        print(confirmpassword)

        if(password != confirmpassword):
            print("password not matched")
            self.errormsg_signup_label = QtWidgets.QLabel(self.centralwidget)
            self.errormsg_signup_label.setGeometry(QtCore.QRect(250,530,55, 16))
            self.errormsg_signup_label.setObjectName("password not matched")
        
        mycursor = self.mydb.cursor()
        mycursor.execute("INSERT INTO sign_up (username, password, website, email, city, Phone_Number) VALUES (%s, %s, %s, %s, %s, %s)", (username, password, website, email, city, phone))

        mycursor.execute("SELECT * FROM sign_up")
        print(mycursor.fetchall())

        self.mydb.commit()





if __name__ == "__main__":

    mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="qwerty123",
    database="login"
    )

    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
   